export type StatutLegal = 'autorise' | 'cites_a_signaler' | 'interdite';

export type CategorieEspece =
  | 'Eau Douce'
  | 'Eau de Mer'
  | 'Bassin'
  | 'Plantes'
  | 'Crustacés / Invertébrés eau douce'
  | 'Mollusques eau douce';

export interface FicheTechnique {
  description: string;
  conseil: string;
  volumeMinLitres: number | null;
  tailleGroupeMin: number | null;
  compatibilite: string;
  incompatibilite: string;
  phMin: number | null;
  phMax: number | null;
  tempMin: number | null;
  tempMax: number | null;
  difficulte: 'Débutant' | 'Intermédiaire' | 'Expert';
  alimentation: string;
  tailleAdulte: string;
}

export interface Espece {
  id: number;
  slug: string;
  categorie: CategorieEspece;
  nomCommun: string;
  nomScientifique: string;
  statutLegal: StatutLegal;
  remarqueLegale: string | null;
  citesAnnexe: string | null;
  // Renseigné uniquement une fois la fiche technique rédigée — voir ESPECES_PUBLIEES.
  fiche?: FicheTechnique;
}

// Catalogue complet des 186 especes de la table de reference interne de l'app
// (statut legal / CITES). Genere une fois depuis un export Supabase, puis enrichi
// manuellement au champ `fiche` au fur et a mesure de la redaction des pages.
// Une espece sans `fiche` existe dans le catalogue mais n'a pas encore de page
// publiee (voir ESPECES_PUBLIEES plus bas).
export const ESPECES: Espece[] = [
  {
    id: 1,
    slug: 'guppy',
    categorie: 'Eau Douce',
    nomCommun: 'Guppy',
    nomScientifique: 'Poecilia reticulata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Le guppy est LE poisson d'aquarium par excellence pour débuter : vivipare (il donne naissance à des alevins déjà formés, pas d'œufs), très coloré chez le mâle, et extrêmement prolifique — une femelle peut donner naissance toutes les 4 à 6 semaines. Robuste et tolérant sur la qualité de l'eau, c'est souvent le premier poisson d'un aquariophile débutant.",
      conseil:
        "Prévoyez toujours plus de femelles que de mâles (au moins 2 pour 1) : les mâles harcèlent sans relâche les femelles pour se reproduire, et un ratio déséquilibré les épuise. Si vous ne voulez pas de reproduction incontrôlée, séparez les sexes ou acceptez de gérer une population croissante.",
      volumeMinLitres: 40,
      tailleGroupeMin: 6,
      compatibilite: "Poissons paisibles de petite taille : corydoras, escargots, crevettes, autres vivipares (molly, platy).",
      incompatibilite: "Poissons qui mordillent les nageoires (barbus de Sumatra) et gros cichlidés susceptibles de les manger.",
      phMin: 7,
      phMax: 8,
      tempMin: 22,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes/granulés du quotidien, complétés occasionnellement par des proies vivantes ou congelées (artémias).",
      tailleAdulte: '3 à 6 cm (le mâle est plus petit et plus coloré que la femelle)',
    },
  },
  {
    id: 2,
    slug: 'molly-voile-noir',
    categorie: 'Eau Douce',
    nomCommun: 'Molly voile noir',
    nomScientifique: 'Poecilia sphenops',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Vivipare à la robe noire uniforme et à la grande nageoire dorsale en voile, le molly est un poisson sociable et actif qui apprécie une eau légèrement dure. Comme le guppy, il se reproduit facilement et donne naissance à des alevins déjà formés.",
      conseil:
        "Le molly apprécie une pincée de sel d'aquarium ou une eau légèrement saumâtre, contrairement à la plupart des poissons d'eau douce — à ne pas partager avec des espèces qui ne tolèrent pas le sel. Comme le guppy, gardez plus de femelles que de mâles.",
      volumeMinLitres: 80,
      tailleGroupeMin: 6,
      compatibilite: "Autres vivipares (guppy, platy), corydoras, poissons paisibles tolérant une eau légèrement dure.",
      incompatibilite: "Poissons exigeant une eau très douce et acide, fin-nippers.",
      phMin: 7.5,
      phMax: 8.5,
      tempMin: 24,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Omnivore avec une tendance algivore : granulés, algues, un peu de matière végétale.",
      tailleAdulte: '8 à 12 cm',
    },
  },
  {
    id: 3,
    slug: 'platy',
    categorie: 'Eau Douce',
    nomCommun: 'Platy',
    nomScientifique: 'Xiphophorus maculatus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Vivipare robuste et coloré, disponible dans de nombreuses variétés (rouge, mickey mouse, wagtail...). Très proche du guppy dans ses besoins, il est un peu plus trapu et légèrement plus calme.",
      conseil:
        "Comme les autres vivipares, gardez plus de femelles que de mâles pour éviter le harcèlement reproductif. Le platy tolère bien une eau plus fraîche que le guppy si besoin, ce qui en fait un bon compagnon de bac non chauffé tempéré.",
      volumeMinLitres: 60,
      tailleGroupeMin: 6,
      compatibilite: "Autres vivipares (guppy, molly), corydoras, tétras paisibles.",
      incompatibilite: "Fin-nippers, gros cichlidés prédateurs.",
      phMin: 7,
      phMax: 8,
      tempMin: 20,
      tempMax: 26,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes/granulés, complément végétal apprécié.",
      tailleAdulte: '4 à 6 cm',
    },
  },
  {
    id: 4,
    slug: 'xipho-porte-epee',
    categorie: 'Eau Douce',
    nomCommun: 'Xipho porte-épée',
    nomScientifique: 'Xiphophorus hellerii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 5,
    slug: 'tetra-neon',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra néon',
    nomScientifique: 'Paracheirodon innesi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petit characidé amazonien à la bande bleu électrique et rouge fluorescente, le tétra néon est l'un des poissons de banc les plus populaires en aquariophilie. Paisible et grégaire, il ne s'épanouit que réuni en groupe nombreux, où ses couleurs ressortent le mieux.",
      conseil:
        "Un petit groupe (moins de 6) stresse et se décolore avec le temps — préférez toujours un banc généreux dans un bac assez long pour qu'il puisse nager en formation. Évitez de l'introduire dans un bac non cyclé, il est sensible aux variations de qualité d'eau.",
      volumeMinLitres: 60,
      tailleGroupeMin: 8,
      compatibilite: "Corydoras, autres petits characidés, crevettes, escargots.",
      incompatibilite: "Gros poissons prédateurs, cichlidés territoriaux qui les considèrent comme des proies.",
      phMin: 5.5,
      phMax: 7,
      tempMin: 20,
      tempMax: 26,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes fines, micro-granulés, artémias.",
      tailleAdulte: '2,5 à 3 cm',
    },
  },
  {
    id: 6,
    slug: 'tetra-cardinal',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra cardinal',
    nomScientifique: 'Paracheirodon axelrodi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 7,
    slug: 'tetra-citron',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra citron',
    nomScientifique: 'Hyphessobrycon pulchripinnis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 8,
    slug: 'tetra-rouge-minor',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra rouge (minor)',
    nomScientifique: 'Hyphessobrycon eques',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 9,
    slug: 'tetra-empereur',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra empereur',
    nomScientifique: 'Nematobrycon palmeri',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 10,
    slug: 'corydoras-de-sterba',
    categorie: 'Eau Douce',
    nomCommun: 'Corydoras de Sterba',
    nomScientifique: 'Corydoras sterbai',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 11,
    slug: 'corydoras-bronze',
    categorie: 'Eau Douce',
    nomCommun: 'Corydoras bronze',
    nomScientifique: 'Corydoras aeneus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petit poisson de fond grégaire et paisible, le corydoras bronze passe son temps à fouiller le substrat à la recherche de restes de nourriture à l'aide de ses barbillons sensoriels. Il remonte aussi régulièrement respirer une bulle d'air en surface, un comportement tout à fait normal.",
      conseil:
        "Le substrat doit être fin et non coupant (sable ou gravier arrondi) : un substrat tranchant abîme ses barbillons au fil du temps. Ne jamais le maintenir seul, il stresse en isolement.",
      volumeMinLitres: 80,
      tailleGroupeMin: 6,
      compatibilite: "Quasiment tous les poissons paisibles de surface et de pleine eau (guppys, tétras, scalaires).",
      incompatibilite: "Cichlidés agressifs, substrat gravier tranchant.",
      phMin: 6,
      phMax: 7.5,
      tempMin: 22,
      tempMax: 26,
      difficulte: 'Débutant',
      alimentation: "Omnivore de fond : pastilles/tablettes spécial poissons de fond, restes de nourriture qui coulent.",
      tailleAdulte: '6 à 7 cm',
    },
  },
  {
    id: 12,
    slug: 'corydoras-panda',
    categorie: 'Eau Douce',
    nomCommun: 'Corydoras panda',
    nomScientifique: 'Corydoras panda',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 13,
    slug: 'corydoras-pygmee',
    categorie: 'Eau Douce',
    nomCommun: 'Corydoras pygmée',
    nomScientifique: 'Corydoras pygmaeus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 14,
    slug: 'combattant-betta',
    categorie: 'Eau Douce',
    nomCommun: 'Combattant / Betta',
    nomScientifique: 'Betta splendens',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Contrairement à l'idée reçue, le combattant n'est pas fait pour vivre dans un petit bocal sans chauffage : dans la nature, il vit dans des rizières et mares peu profondes mais chaudes. Son organe labyrinthique lui permet de respirer l'air en surface, ce qui explique sa réputation (fausse) de poisson increvable en bocal. Très territorial, un mâle ne tolère aucun autre mâle de son espèce.",
      conseil:
        "Un aquarium chauffé avec couvercle est indispensable (le betta est un excellent sauteur). Ne jamais mettre deux mâles ensemble, et éviter les poissons aux nageoires voilées qui pourraient être pris pour un rival.",
      volumeMinLitres: 20,
      tailleGroupeMin: 1,
      compatibilite: "Crevettes calmes, escargots, poissons de fond paisibles (corydoras) qui ne s'approchent pas de sa zone.",
      incompatibilite: "Un autre mâle combattant, poissons aux nageoires longues/colorées (confondus avec un rival), poissons mordilleurs de nageoires.",
      phMin: 6.5,
      phMax: 7.5,
      tempMin: 24,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Carnivore : granulés spécifiques betta, larves de moustique congelées.",
      tailleAdulte: '6 à 7 cm',
    },
  },
  {
    id: 15,
    slug: 'scalaire',
    categorie: 'Eau Douce',
    nomCommun: 'Scalaire',
    nomScientifique: 'Pterophyllum scalare',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Cichlidé amazonien à la silhouette aplatie et triangulaire caractéristique, le scalaire grandit surtout en hauteur (jusqu'à 25 cm avec les nageoires). Grégaire à l'état juvénile, il forme des couples stables à l'âge adulte et peut devenir territorial pendant la reproduction.",
      conseil:
        "Prévoyez un bac assez haut (50 cm minimum) plutôt que large. Achetez un groupe de 5-6 jeunes pour qu'ils forment naturellement des couples, plutôt que d'imposer un couple choisi au hasard.",
      volumeMinLitres: 200,
      tailleGroupeMin: 5,
      compatibilite: "Characidés de taille moyenne, corydoras, autres cichlidés paisibles amazoniens.",
      incompatibilite: "Petits poissons et crevettes (deviennent des proies une fois le scalaire adulte), poissons mordilleurs de nageoires.",
      phMin: 6,
      phMax: 7.5,
      tempMin: 25,
      tempMax: 29,
      difficulte: 'Intermédiaire',
      alimentation: "Omnivore : granulés/paillettes, complétés par des vers de vase et artémias congelés.",
      tailleAdulte: '12 à 15 cm de long (jusqu’à 25 cm de hauteur avec les nageoires)',
    },
  },
  {
    id: 16,
    slug: 'discus',
    categorie: 'Eau Douce',
    nomCommun: 'Discus',
    nomScientifique: 'Symphysodon aequifasciatus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Cichlidé amazonien au corps discoïdal et aux couleurs spectaculaires, le discus a la réputation méritée d'être exigeant : il demande une eau douce et stable, des changements d'eau réguliers, et ne tolère pas les variations brutales de paramètres. Grégaire, il vit en groupe hiérarchisé.",
      conseil:
        "Ce n'est pas un poisson pour un premier aquarium : réservez-le à un bac déjà mature et stable depuis plusieurs mois, avec des changements d'eau fréquents (20-30% par semaine). Attendez d'avoir de l'expérience avec des espèces plus tolérantes avant de vous lancer.",
      volumeMinLitres: 300,
      tailleGroupeMin: 6,
      compatibilite: "Autres cichlidés amazoniens calmes, characidés de taille moyenne, corydoras.",
      incompatibilite: "Poissons rapides et stressants, eau dure ou instable, bac récemment cyclé.",
      phMin: 6,
      phMax: 7,
      tempMin: 28,
      tempMax: 30,
      difficulte: 'Expert',
      alimentation: "Omnivore : granulés spécifiques discus, vers de vase et cœur de bœuf congelés.",
      tailleAdulte: '15 à 20 cm',
    },
  },
  {
    id: 17,
    slug: 'gourami-nain',
    categorie: 'Eau Douce',
    nomCommun: 'Gourami nain',
    nomScientifique: 'Trichogaster lalius',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petit labyrinthidé coloré (le mâle arbore des rayures bleues et rouges), le gourami nain respire l'air atmosphérique en surface grâce à son organe labyrinthique, comme le combattant. Plutôt calme, il peut devenir un peu territorial en période de reproduction.",
      conseil:
        "Évitez plusieurs mâles dans un petit bac, ils se disputent le territoire. Le gourami nain apprécie une surface végétalisée (plantes flottantes) qui rappelle son habitat naturel de mares calmes.",
      volumeMinLitres: 60,
      tailleGroupeMin: 1,
      compatibilite: "Poissons paisibles de banc (tétras, corydoras), crevettes.",
      incompatibilite: "Autres labyrinthidés mâles territoriaux, poissons très agités qui le stressent.",
      phMin: 6,
      phMax: 7.5,
      tempMin: 24,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes, granulés, larves congelées occasionnelles.",
      tailleAdulte: '5 à 8 cm',
    },
  },
  {
    id: 18,
    slug: 'gourami-perle',
    categorie: 'Eau Douce',
    nomCommun: 'Gourami perlé',
    nomScientifique: 'Trichopodus leerii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 19,
    slug: 'gourami-miel',
    categorie: 'Eau Douce',
    nomCommun: 'Gourami miel',
    nomScientifique: 'Trichogaster chuna',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 20,
    slug: 'danio-zebre',
    categorie: 'Eau Douce',
    nomCommun: 'Danio zébré',
    nomScientifique: 'Danio rerio',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petit poisson rayé très vif et rustique, le danio zébré est un excellent choix pour un bac communautaire débutant : robuste, tolérant sur la température, et infatigable nageur de pleine eau. C'est aussi l'un des organismes modèles les plus utilisés en recherche scientifique.",
      conseil:
        "Très actif et rapide, il a besoin d'un bac assez long pour nager en banc — évitez les bacs trop hauts et étroits. Sa vivacité peut stresser des poissons plus lents ou timides partagés dans un espace restreint.",
      volumeMinLitres: 60,
      tailleGroupeMin: 6,
      compatibilite: "Autres danios, corydoras, poissons de fond calmes qui ne partagent pas sa zone de nage.",
      incompatibilite: "Poissons très lents ou aux longues nageoires (risque de mordillement par jeu), bettas.",
      phMin: 6.5,
      phMax: 7.5,
      tempMin: 18,
      tempMax: 24,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes, granulés, très peu difficile.",
      tailleAdulte: '4 à 5 cm',
    },
  },
  {
    id: 21,
    slug: 'danio-leopard',
    categorie: 'Eau Douce',
    nomCommun: 'Danio léopard',
    nomScientifique: 'Danio rerio (var.)',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 22,
    slug: 'barbus-de-sumatra',
    categorie: 'Eau Douce',
    nomCommun: 'Barbus de Sumatra',
    nomScientifique: 'Puntigrus tetrazona',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Poisson rayé actif et grégaire, tristement connu pour mordiller les nageoires des poissons plus lents ou aux voiles longues quand il est maintenu en trop petit nombre. En banc suffisamment nombreux, ce comportement disparaît presque entièrement : l'énergie du groupe se dirige vers ses propres congénères plutôt que vers les autres espèces.",
      conseil:
        "La règle d'or : jamais moins de 8-10 individus. Un petit groupe de 3-4 barbus de Sumatra devient quasi systématiquement un problème pour les poissons à nageoires longues du bac (guppy, betta, voile de Chine).",
      volumeMinLitres: 100,
      tailleGroupeMin: 8,
      compatibilite: "Autres poissons robustes et rapides sans grandes nageoires (danios, autres barbus).",
      incompatibilite: "Bettas, guppys, voiles de Chine et tout poisson aux nageoires longues — surtout si le groupe est trop petit.",
      phMin: 6,
      phMax: 7.5,
      tempMin: 22,
      tempMax: 26,
      difficulte: 'Débutant',
      alimentation: "Omnivore : paillettes, granulés, un peu de végétal.",
      tailleAdulte: '5 à 7 cm',
    },
  },
  {
    id: 23,
    slug: 'barbus-cerise',
    categorie: 'Eau Douce',
    nomCommun: 'Barbus cerise',
    nomScientifique: 'Puntius titteya',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 24,
    slug: 'barbus-rose',
    categorie: 'Eau Douce',
    nomCommun: 'Barbus rosé',
    nomScientifique: 'Pethia conchonius',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 25,
    slug: 'loche-clown',
    categorie: 'Eau Douce',
    nomCommun: 'Loche clown',
    nomScientifique: 'Chromobotia macracanthus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 26,
    slug: 'loche-kuhli',
    categorie: 'Eau Douce',
    nomCommun: 'Loche kuhli',
    nomScientifique: 'Pangio kuhlii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 27,
    slug: 'ancistrus-plecos-commun',
    categorie: 'Eau Douce',
    nomCommun: 'Ancistrus / plecos commun',
    nomScientifique: 'Ancistrus sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petit pléco nocturne surtout connu pour son rôle de nettoyeur de vitres et de décor (algues). Le mâle adulte développe des excroissances ressemblant à des tentacules sur le museau, absentes chez la femelle. Discret le jour, actif la nuit.",
      conseil:
        "Fournissez impérativement une racine de bois flotté : l'ancistrus en râcle des fibres qui l'aident à digérer, indépendamment de son régime alimentaire. Évitez plusieurs mâles adultes dans un bac trop petit, ils se disputent les cachettes.",
      volumeMinLitres: 100,
      tailleGroupeMin: 1,
      compatibilite: "Quasiment tous les poissons paisibles ; cohabite bien en solitaire ou en couple.",
      incompatibilite: "Plusieurs mâles adultes ensemble dans un espace restreint (bagarres territoriales).",
      phMin: 6.5,
      phMax: 7.5,
      tempMin: 23,
      tempMax: 27,
      difficulte: 'Débutant',
      alimentation: "Algivore/omnivore : pastilles à base de spiruline, légumes blanchis (courgette, concombre), bois flotté.",
      tailleAdulte: '12 à 15 cm',
    },
  },
  {
    id: 28,
    slug: 'pleco-commun',
    categorie: 'Eau Douce',
    nomCommun: 'Pléco commun',
    nomScientifique: 'Hypostomus plecostomus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 29,
    slug: 'kribensis',
    categorie: 'Eau Douce',
    nomCommun: 'Kribensis',
    nomScientifique: 'Pelvicachromis pulcher',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 30,
    slug: 'apistogramma-cacatuoides',
    categorie: 'Eau Douce',
    nomCommun: 'Apistogramma cacatuoides',
    nomScientifique: 'Apistogramma cacatuoides',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 31,
    slug: 'poisson-arc-en-ciel',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson arc-en-ciel',
    nomScientifique: 'Melanotaenia boesemani',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 32,
    slug: 'killie-nothobranchius',
    categorie: 'Eau Douce',
    nomCommun: 'Killie (nothobranchius)',
    nomScientifique: 'Nothobranchius rachovii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 33,
    slug: 'otocinclus',
    categorie: 'Eau Douce',
    nomCommun: 'Otocinclus',
    nomScientifique: 'Otocinclus affinis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 34,
    slug: 'colisa-lalia-gourami-nain-multicolore',
    categorie: 'Eau Douce',
    nomCommun: 'Colisa lalia (gourami nain multicolore)',
    nomScientifique: 'Trichogaster lalius',
    statutLegal: 'autorise',
    remarqueLegale: 'doublon fonctionnel avec gourami nain - à fusionner en base',
    citesAnnexe: null,
  },
  {
    id: 35,
    slug: 'rasbora-arlequin',
    categorie: 'Eau Douce',
    nomCommun: 'Rasbora arlequin',
    nomScientifique: 'Trigonostigma heteromorpha',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 36,
    slug: 'rasbora-tete-de-cuivre',
    categorie: 'Eau Douce',
    nomCommun: 'Rasbora tête de cuivre',
    nomScientifique: 'Rasbora rasbora',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 37,
    slug: 'poisson-chat-de-verre',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat de verre',
    nomScientifique: 'Kryptopterus vitreolus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 38,
    slug: 'poisson-archer',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson archer',
    nomScientifique: 'Toxotes jaculatrix',
    statutLegal: 'autorise',
    remarqueLegale: 'vit aussi en eau saumâtre - pas d\'interdiction mais besoins spécifiques',
    citesAnnexe: null,
  },
  {
    id: 39,
    slug: 'ram-papiliochromis',
    categorie: 'Eau Douce',
    nomCommun: 'Ram / Papiliochromis',
    nomScientifique: 'Mikrogeophagus ramirezi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 40,
    slug: 'poisson-chat-pictus',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat pictus',
    nomScientifique: 'Pimelodus pictus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 41,
    slug: 'molly-ballon',
    categorie: 'Eau Douce',
    nomCommun: 'Molly ballon',
    nomScientifique: 'Poecilia sphenops (var.)',
    statutLegal: 'autorise',
    remarqueLegale: 'forme sélective - débat bien-être animal mais pas d\'interdiction légale',
    citesAnnexe: null,
  },
  {
    id: 42,
    slug: 'requin-arc-en-ciel',
    categorie: 'Eau Douce',
    nomCommun: 'Requin arc-en-ciel',
    nomScientifique: 'Epalzeorhynchos frenatum',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 43,
    slug: 'requin-a-queue-rouge',
    categorie: 'Eau Douce',
    nomCommun: 'Requin à queue rouge',
    nomScientifique: 'Epalzeorhynchos bicolor',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 44,
    slug: 'poisson-lune-metynnis',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-lune / Metynnis',
    nomScientifique: 'Metynnis argenteus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 45,
    slug: 'poisson-hachette',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-hachette',
    nomScientifique: 'Carnegiella strigata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 46,
    slug: 'anableps-poisson-a-quatre-yeux',
    categorie: 'Eau Douce',
    nomCommun: 'Anableps / poisson à quatre yeux',
    nomScientifique: 'Anableps anableps',
    statutLegal: 'autorise',
    remarqueLegale: 'espèce peu courante nécessitant des conditions spécifiques - à faire valider au cas par cas plutôt qu\'en libre-service',
    citesAnnexe: null,
  },
  {
    id: 47,
    slug: 'poisson-couteau',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-couteau',
    nomScientifique: 'Apteronotus albifrons',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 48,
    slug: 'poisson-elephant-mormyridae',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-éléphant (Mormyridae)',
    nomScientifique: 'Gnathonemus petersii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 49,
    slug: 'poisson-clown-d-eau-douce-chromobotia',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-clown d\'eau douce (Chromobotia)',
    nomScientifique: 'Chromobotia macracanthus',
    statutLegal: 'autorise',
    remarqueLegale: 'doublon avec loche clown - à fusionner en base',
    citesAnnexe: null,
  },
  {
    id: 50,
    slug: 'raie-d-eau-douce-potamotrygon-motoro',
    categorie: 'Eau Douce',
    nomCommun: 'Raie d\'eau douce (Potamotrygon motoro)',
    nomScientifique: 'Potamotrygon motoro',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'famille Potamotrygonidae - certaines espèces listées CITES Annexe III depuis 2019 et soumises à traçabilité renforcée - toujours orienter vers demande de validation',
    citesAnnexe: 'C',
  },
  {
    id: 51,
    slug: 'arowana-asiatique',
    categorie: 'Eau Douce',
    nomCommun: 'Arowana asiatique',
    nomScientifique: 'Scleropages formosus',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'CITES Annexe I - vente strictement encadrée (puce électronique + certificat individuel obligatoire) - ne jamais autoriser en libre-service',
    citesAnnexe: 'A',
  },
  {
    id: 52,
    slug: 'esturgeon-nain',
    categorie: 'Eau Douce',
    nomCommun: 'Esturgeon nain',
    nomScientifique: 'Acipenser ruthenus (formes naines)',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'famille des esturgeons listée CITES Annexe II - vérification au cas par cas',
    citesAnnexe: 'B',
  },
  {
    id: 53,
    slug: 'carpe-koi',
    categorie: 'Bassin',
    nomCommun: 'Carpe koï',
    nomScientifique: 'Cyprinus rubrofuscus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Variété ornementale de carpe sélectionnée pour ses couleurs, la koï grandit énormément (jusqu'à 90 cm) et peut vivre plusieurs décennies. Sociable, elle reconnaît son propriétaire et vient souvent chercher la nourriture à la main avec le temps.",
      conseil:
        "La koï est un poisson de bassin extérieur, pas d'aquarium, sur le long terme — sa taille adulte l'impose. Prévoyez une zone d'au moins 80 cm de profondeur pour qu'elle puisse hiverner sans risque de gel complet du bassin.",
      volumeMinLitres: 3000,
      tailleGroupeMin: 5,
      compatibilite: "Autres carpes koï, poissons rouges, tanches (nettoyeuses de fond).",
      incompatibilite: "Petit bassin sans filtration puissante, bassin qui gèle entièrement en hiver faute de zone profonde.",
      phMin: 7,
      phMax: 8,
      tempMin: 4,
      tempMax: 28,
      difficulte: 'Intermédiaire',
      alimentation: "Omnivore : granulés flottants spécial koï, alimentation réduite voire stoppée en dessous de 10°C.",
      tailleAdulte: '40 à 90 cm selon la variété et le volume du bassin',
    },
  },
  {
    id: 54,
    slug: 'poisson-rouge-carassin-dore',
    categorie: 'Bassin',
    nomCommun: 'Poisson rouge / Carassin doré',
    nomScientifique: 'Carassius auratus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Souvent vendu comme petit poisson de bocal, le poisson rouge est en réalité un poisson de bassin à part entière : il peut atteindre 20-30 cm et vivre plus de 20 ans dans de bonnes conditions. Grégaire et très résistant au froid, il hiberne dans les zones profondes d'un bassin en hiver.",
      conseil:
        "Le mythe du \"petit bocal\" est l'une des principales causes de mortalité précoce de cette espèce : sans volume suffisant, sa croissance est stoppée et sa santé se dégrade. Un bassin extérieur ou un grand aquarium (300 L+) sont le minimum pour un groupe adulte.",
      volumeMinLitres: 300,
      tailleGroupeMin: 3,
      compatibilite: "Autres poissons rouges, carpes koï calmes, tanches nettoyeuses de fond.",
      incompatibilite: "Petit bocal sans filtration, poissons tropicaux nécessitant une eau chauffée.",
      phMin: 7,
      phMax: 8,
      tempMin: 4,
      tempMax: 24,
      difficulte: 'Débutant',
      alimentation: "Omnivore : granulés flottants, un peu de végétal, alimentation réduite en dessous de 10°C.",
      tailleAdulte: '15 à 30 cm selon le volume disponible',
    },
  },
  {
    id: 55,
    slug: 'tanche',
    categorie: 'Bassin',
    nomCommun: 'Tanche',
    nomScientifique: 'Tinca tinca',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 56,
    slug: 'vairon',
    categorie: 'Bassin',
    nomCommun: 'Vairon',
    nomScientifique: 'Phoxinus phoxinus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 57,
    slug: 'loche-de-bassin',
    categorie: 'Bassin',
    nomCommun: 'Loche de bassin',
    nomScientifique: 'Misgurnus anguillicaudatus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espece exotique envahissante (population etablie en France) - vente interdite.',
    citesAnnexe: null,
  },
  {
    id: 58,
    slug: 'ide-melanote',
    categorie: 'Bassin',
    nomCommun: 'Ide mélanote',
    nomScientifique: 'Leuciscus idus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 59,
    slug: 'amour-blanc',
    categorie: 'Bassin',
    nomCommun: 'Amour blanc',
    nomScientifique: 'Ctenopharyngodon idella',
    statutLegal: 'autorise',
    remarqueLegale: 'détention réglementée dans certains départements en dehors de bassins clos et étanches - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 60,
    slug: 'poisson-clown-ocellaris',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-clown ocellaris',
    nomScientifique: 'Amphiprion ocellaris',
    statutLegal: 'autorise',
    remarqueLegale: 'quasi-totalité des sujets vendus sont nés en élevage',
    citesAnnexe: null,
    fiche: {
      description:
        "Poisson marin emblématique, rendu célèbre par le cinéma d'animation. Il vit naturellement en symbiose avec des anémones de mer, mais s'en passe très bien en aquarium récifal. Sa hiérarchie sociale est stricte : la femelle est toujours l'individu dominant et le plus grand du groupe.",
      conseil:
        "Privilégiez toujours un sujet né en élevage (c'est aujourd'hui la quasi-totalité de ceux vendus) plutôt qu'un prélèvement sauvage : plus résistant et sans impact sur les populations naturelles. Introduisez-le seul ou en couple déjà formé — deux individus non appariés se bagarrent souvent.",
      volumeMinLitres: 100,
      tailleGroupeMin: 1,
      compatibilite: "Gobies, demoiselles calmes, crevettes de nettoyage.",
      incompatibilite: "Autres poissons-clowns non appariés dans un espace restreint, poissons très territoriaux.",
      phMin: 8.1,
      phMax: 8.4,
      tempMin: 24,
      tempMax: 27,
      difficulte: 'Intermédiaire',
      alimentation: "Omnivore : granulés/paillettes marines, artémias et mysis congelés.",
      tailleAdulte: '8 à 9 cm',
    },
  },
  {
    id: 61,
    slug: 'poisson-clown-percula',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-clown percula',
    nomScientifique: 'Amphiprion percula',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 62,
    slug: 'chirurgien-bleu',
    categorie: 'Eau de Mer',
    nomCommun: 'Chirurgien bleu',
    nomScientifique: 'Paracanthurus hepatus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 63,
    slug: 'chirurgien-voile-jaune',
    categorie: 'Eau de Mer',
    nomCommun: 'Chirurgien voile jaune',
    nomScientifique: 'Zebrasoma flavescens',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 64,
    slug: 'demoiselle-bleue',
    categorie: 'Eau de Mer',
    nomCommun: 'Demoiselle bleue',
    nomScientifique: 'Chrysiptera cyanea',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 65,
    slug: 'demoiselle-verte',
    categorie: 'Eau de Mer',
    nomCommun: 'Demoiselle verte',
    nomScientifique: 'Chromis viridis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 66,
    slug: 'labre-nettoyeur',
    categorie: 'Eau de Mer',
    nomCommun: 'Labre nettoyeur',
    nomScientifique: 'Labroides dimidiatus',
    statutLegal: 'autorise',
    remarqueLegale: 'se nourrit exclusivement de parasites sur d\'autres poissons - à déconseiller en aquarium mais pas interdit',
    citesAnnexe: null,
  },
  {
    id: 67,
    slug: 'poisson-ange-nain',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-ange nain',
    nomScientifique: 'Centropyge loriculus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 68,
    slug: 'poisson-perroquet',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-perroquet',
    nomScientifique: 'Scarus sp.',
    statutLegal: 'autorise',
    remarqueLegale: 'rarement adapté à l\'aquarium (taille adulte, alimentation corallienne) - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 69,
    slug: 'gobie-crevette',
    categorie: 'Eau de Mer',
    nomCommun: 'Gobie crevette',
    nomScientifique: 'Cryptocentrus cinctus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 70,
    slug: 'blennie-leopard',
    categorie: 'Eau de Mer',
    nomCommun: 'Blennie léopard',
    nomScientifique: 'Salarias fasciatus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 71,
    slug: 'poisson-lion-volant',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-lion volant',
    nomScientifique: 'Pterois volitans',
    statutLegal: 'autorise',
    remarqueLegale: 'venimeux - vente tolérée mais à signaler pour rappel des précautions à l\'acheteur, pas d\'interdiction',
    citesAnnexe: null,
  },
  {
    id: 72,
    slug: 'hippocampe',
    categorie: 'Eau de Mer',
    nomCommun: 'Hippocampe',
    nomScientifique: 'Hippocampus sp.',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'genre entier listé CITES Annexe II - certificat de cession et traçabilité obligatoires, ne jamais autoriser en libre-service',
    citesAnnexe: 'B',
  },
  {
    id: 73,
    slug: 'benitier-tridacna',
    categorie: 'Eau de Mer',
    nomCommun: 'Bénitier / Tridacna',
    nomScientifique: 'Tridacna maxima',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'CITES Annexe II - certificat obligatoire',
    citesAnnexe: 'B',
  },
  {
    id: 74,
    slug: 'corail-dur-sps-lps-genre-acropora',
    categorie: 'Eau de Mer',
    nomCommun: 'Corail dur (SPS/LPS genre Acropora)',
    nomScientifique: 'Acropora sp.',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'tous les coraux durs scléractiniaires sont Annexe B UE / CITES, y compris les boutures - toujours orienter vers demande de validation',
    citesAnnexe: 'B',
  },
  {
    id: 75,
    slug: 'corail-marteau',
    categorie: 'Eau de Mer',
    nomCommun: 'Corail marteau',
    nomScientifique: 'Euphyllia ancora',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'idem corail dur',
    citesAnnexe: 'B',
  },
  {
    id: 76,
    slug: 'corail-mou-genre-sarcophyton',
    categorie: 'Eau de Mer',
    nomCommun: 'Corail mou (genre Sarcophyton)',
    nomScientifique: 'Sarcophyton sp.',
    statutLegal: 'autorise',
    remarqueLegale: 'coraux mous non scléractiniaires généralement non listés CITES - à confirmer espèce par espèce si doute',
    citesAnnexe: null,
  },
  {
    id: 77,
    slug: 'anemone-bulbe',
    categorie: 'Eau de Mer',
    nomCommun: 'Anémone bulbe',
    nomScientifique: 'Entacmaea quadricolor',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 78,
    slug: 'anemone-a-tapis',
    categorie: 'Eau de Mer',
    nomCommun: 'Anémone à tapis',
    nomScientifique: 'Heteractis sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 79,
    slug: 'crevette-nettoyeuse',
    categorie: 'Eau de Mer',
    nomCommun: 'Crevette nettoyeuse',
    nomScientifique: 'Lysmata amboinensis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 80,
    slug: 'crevette-pistolet',
    categorie: 'Eau de Mer',
    nomCommun: 'Crevette pistolet',
    nomScientifique: 'Alpheus sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 81,
    slug: 'bernard-l-ermite-marin',
    categorie: 'Eau de Mer',
    nomCommun: 'Bernard-l\'ermite marin',
    nomScientifique: 'Clibanarius sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 82,
    slug: 'etoile-de-mer-bleue',
    categorie: 'Eau de Mer',
    nomCommun: 'Étoile de mer bleue',
    nomScientifique: 'Linckia laevigata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 83,
    slug: 'escargot-turbo',
    categorie: 'Eau de Mer',
    nomCommun: 'Escargot Turbo',
    nomScientifique: 'Turbo fluctuosa',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 84,
    slug: 'escargot-nassarius',
    categorie: 'Eau de Mer',
    nomCommun: 'Escargot Nassarius',
    nomScientifique: 'Nassarius sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 85,
    slug: 'cone-conus-textile',
    categorie: 'Eau de Mer',
    nomCommun: 'Cône (Conus textile)',
    nomScientifique: 'Conus textile',
    statutLegal: 'autorise',
    remarqueLegale: 'venin potentiellement mortel pour l\'humain - à ne pas mettre en libre-service, orienter systématiquement vers demande de validation par précaution',
    citesAnnexe: null,
  },
  {
    id: 86,
    slug: 'crevette-red-cherry',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette Red Cherry',
    nomScientifique: 'Neocaridina davidi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Petite crevette d'eau douce très facile à maintenir et à reproduire dans un bac mature — une population s'installe souvent d'elle-même sans intervention. Excellent indicateur de la qualité de l'eau : elle est très sensible aux pics d'ammoniac et de nitrites.",
      conseil:
        "Ne traitez jamais un bac qui héberge des crevettes avec un médicament à base de cuivre : c'est mortel pour elles, même à faible dose. Attention aussi à tout poisson introduit par la suite, qui pourrait chasser les juvéniles.",
      volumeMinLitres: 20,
      tailleGroupeMin: 10,
      compatibilite: "Autres crevettes Neocaridina, escargots, poissons très calmes et non prédateurs.",
      incompatibilite: "La plupart des poissons (prédateurs des juvéniles, parfois des adultes), traitements à base de cuivre.",
      phMin: 6.5,
      phMax: 8,
      tempMin: 20,
      tempMax: 26,
      difficulte: 'Débutant',
      alimentation: "Omnivore/détritivore : algues, biofilm, granulés spécifiques crevettes, légumes blanchis.",
      tailleAdulte: '2 à 3 cm',
    },
  },
  {
    id: 87,
    slug: 'crevette-crystal-red',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette Crystal Red',
    nomScientifique: 'Caridina cantonensis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 88,
    slug: 'crevette-amano',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette Amano',
    nomScientifique: 'Caridina multidentata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 89,
    slug: 'crevette-fantome',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette fantôme',
    nomScientifique: 'Palaemonetes paludosus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 90,
    slug: 'escargot-mystere',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot mystère',
    nomScientifique: 'Pomacea bridgesii',
    statutLegal: 'autorise',
    remarqueLegale: 'le genre Pomacea contient des espèces invasives interdites (P. canaliculata, P. maculata) très proches visuellement - à valider au cas par cas plutôt qu\'en libre-service',
    citesAnnexe: null,
  },
  {
    id: 91,
    slug: 'neritine',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Néritine',
    nomScientifique: 'Neritina natalensis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Escargot d'eau douce parmi les plus appréciés pour lutter contre les algues : il en consomme de grandes quantités sans jamais toucher aux plantes saines, contrairement à d'autres espèces plus opportunistes. Sa coquille présente des motifs variés selon les variétés (zébrée, tigrée, à cornes...).",
      conseil:
        "La néritine ne se reproduit pas en eau douce (elle a besoin d'eau saumâtre pour ses larves) : pas de risque de prolifération incontrôlée, contrairement aux escargots planorbes ou physes. Les œufs blancs qu'elle pond sur le décor n'écloront donc jamais en aquarium d'eau douce pure.",
      volumeMinLitres: 20,
      tailleGroupeMin: 1,
      compatibilite: "Quasiment tous les poissons et invertébrés paisibles ; excellent compagnon des bacs à crevettes.",
      incompatibilite: "Poissons mangeurs d'escargots (certains botias, certains cichlidés).",
      phMin: 7,
      phMax: 8.5,
      tempMin: 22,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Algivore : algues et biofilm ; complément de pastilles à base de spiruline si les algues manquent.",
      tailleAdulte: '2 à 2,5 cm',
    },
  },
  {
    id: 92,
    slug: 'planorbe-rouge',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Planorbe rouge',
    nomScientifique: 'Planorbella duryi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 93,
    slug: 'physe',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Physe',
    nomScientifique: 'Physa acuta',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 94,
    slug: 'escargot-trompette-de-malaisie',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot trompette de Malaisie',
    nomScientifique: 'Melanoides tuberculata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 95,
    slug: 'mousse-de-java',
    categorie: 'Plantes',
    nomCommun: 'Mousse de Java',
    nomScientifique: 'Taxiphyllum barbieri',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Mousse aquatique parmi les plus populaires en aquariophilie, elle se fixe sur du bois flotté ou de la roche et forme un tapis dense à croissance lente à modérée. C'est un excellent abri pour les alevins et les crevettes, qui y trouvent nourriture et protection.",
      conseil:
        "Fixez-la sur son support avec du fil de coton ou de la colle cyanoacrylate gel spéciale aquarium le temps qu'elle s'accroche naturellement (quelques semaines). Taillez-la régulièrement pour éviter que l'intérieur du tapis ne pourrisse faute de lumière.",
      volumeMinLitres: null,
      tailleGroupeMin: null,
      compatibilite: "Convient à la quasi-totalité des bacs d'eau douce, particulièrement adaptée aux bacs à crevettes et à alevins.",
      incompatibilite: "Poissons herbivores qui la grignotent (certains cichlidés, poissons-chats herbivores).",
      phMin: 5.5,
      phMax: 8,
      tempMin: 15,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Photosynthèse : une lumière faible à modérée suffit, le CO2 additionnel n'est pas indispensable.",
      tailleAdulte: "Tapis de quelques millimètres à plusieurs centimètres d'épaisseur selon l'entretien",
    },
  },
  {
    id: 96,
    slug: 'anubias-nana',
    categorie: 'Plantes',
    nomCommun: 'Anubias nana',
    nomScientifique: 'Anubias barteri var. nana',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
    fiche: {
      description:
        "Plante d'aquarium parmi les plus faciles et les plus utilisées en aquascaping, l'anubias nana se fixe sur du bois ou de la roche plutôt que dans le substrat. Sa croissance très lente et ses feuilles épaisses et coriaces la rendent quasiment indestructible.",
      conseil:
        "Ne jamais enterrer le rhizome (la tige horizontale) dans le substrat : il doit rester à l'air libre, sinon il pourrit. Fixez-la avec du fil ou de la colle sur un support jusqu'à ce que les racines s'accrochent naturellement.",
      volumeMinLitres: null,
      tailleGroupeMin: null,
      compatibilite: "Convient à la quasi-totalité des bacs d'eau douce, y compris ceux avec des poissons herbivores (résiste bien au grignotage grâce à ses feuilles coriaces).",
      incompatibilite: "Aucune incompatibilité notable ; à éviter d'enterrer le rhizome.",
      phMin: 6,
      phMax: 7.5,
      tempMin: 22,
      tempMax: 28,
      difficulte: 'Débutant',
      alimentation: "Photosynthèse : pousse même en lumière faible, CO2 non indispensable.",
      tailleAdulte: '10 à 15 cm de hauteur',
    },
  },
  {
    id: 97,
    slug: 'cryptocoryne-wendtii',
    categorie: 'Plantes',
    nomCommun: 'Cryptocoryne wendtii',
    nomScientifique: 'Cryptocoryne wendtii',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 98,
    slug: 'echinodorus-epee-d-amazone',
    categorie: 'Plantes',
    nomCommun: 'Echinodorus / épée d\'Amazone',
    nomScientifique: 'Echinodorus bleherae',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 99,
    slug: 'vallisneria-spiralis',
    categorie: 'Plantes',
    nomCommun: 'Vallisneria spiralis',
    nomScientifique: 'Vallisneria spiralis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 100,
    slug: 'fougere-de-java',
    categorie: 'Plantes',
    nomCommun: 'Fougère de Java',
    nomScientifique: 'Microsorum pteropus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 101,
    slug: 'hygrophila-polysperma',
    categorie: 'Plantes',
    nomCommun: 'Hygrophila polysperma',
    nomScientifique: 'Hygrophila polysperma',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 102,
    slug: 'rotala-rotundifolia',
    categorie: 'Plantes',
    nomCommun: 'Rotala rotundifolia',
    nomScientifique: 'Rotala rotundifolia',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 103,
    slug: 'ludwigia-repens',
    categorie: 'Plantes',
    nomCommun: 'Ludwigia repens',
    nomScientifique: 'Ludwigia repens',
    statutLegal: 'autorise',
    remarqueLegale: 'à ne pas confondre avec Ludwigia grandiflora/peploides (jussie) qui sont interdites - vérifier le nom d\'espèce exact avant tout ajout en base',
    citesAnnexe: null,
  },
  {
    id: 104,
    slug: 'lentille-d-eau-lemna-minor',
    categorie: 'Plantes',
    nomCommun: 'Lentille d\'eau (Lemna minor)',
    nomScientifique: 'Lemna minor',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 105,
    slug: 'cichlide-zebre-du-malawi',
    categorie: 'Eau Douce',
    nomCommun: 'Cichlidé zébré du Malawi',
    nomScientifique: 'Pseudotropheus zebra',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 106,
    slug: 'cichlide-frontosa-tanganyika',
    categorie: 'Eau Douce',
    nomCommun: 'Cichlidé Frontosa (Tanganyika)',
    nomScientifique: 'Cyphotilapia frontosa',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 107,
    slug: 'cichlide-paon-aulonocara',
    categorie: 'Eau Douce',
    nomCommun: 'Cichlidé paon (Aulonocara)',
    nomScientifique: 'Aulonocara nyassae',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 108,
    slug: 'oscar',
    categorie: 'Eau Douce',
    nomCommun: 'Oscar',
    nomScientifique: 'Astronotus ocellatus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 109,
    slug: 'poisson-perroquet-nain-convict',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-perroquet nain (Convict)',
    nomScientifique: 'Amatitlania nigrofasciata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 110,
    slug: 'gourami-geant',
    categorie: 'Eau Douce',
    nomCommun: 'Gourami géant',
    nomScientifique: 'Osphronemus goramy',
    statutLegal: 'autorise',
    remarqueLegale: 'taille adulte importante (jusqu\'à 60-70 cm) - à valider au cas par cas pour vérifier la compatibilité avec un aquarium domestique',
    citesAnnexe: null,
  },
  {
    id: 111,
    slug: 'poisson-chat-requin-pangasius',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat requin / Pangasius',
    nomScientifique: 'Pangasianodon hypophthalmus',
    statutLegal: 'autorise',
    remarqueLegale: 'taille adulte très importante et inadaptée à l\'aquarium domestique - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 112,
    slug: 'tetra-rouge-du-congo',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra rouge du Congo',
    nomScientifique: 'Phenacogrammus interruptus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 113,
    slug: 'tetra-glowlight',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra glowlight',
    nomScientifique: 'Hemigrammus erythrozonus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 114,
    slug: 'tetra-a-queue-rouge',
    categorie: 'Eau Douce',
    nomCommun: 'Tétra à queue rouge',
    nomScientifique: 'Hemigrammus bleheri',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 115,
    slug: 'poisson-arlequin-cuivre',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson arlequin cuivré',
    nomScientifique: 'Trigonostigma espei',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 116,
    slug: 'poisson-clown-loche-yoyo',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-clown loche (Yoyo)',
    nomScientifique: 'Botia almorhae',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 117,
    slug: 'xenotoca-poisson-a-queue-rouge',
    categorie: 'Eau Douce',
    nomCommun: 'Xénotoca / poisson à queue rouge',
    nomScientifique: 'Xenotoca eiseni',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 118,
    slug: 'molly-voile-de-lyre',
    categorie: 'Eau Douce',
    nomCommun: 'Molly voile de Lyre',
    nomScientifique: 'Poecilia latipinna',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 119,
    slug: 'endler',
    categorie: 'Eau Douce',
    nomCommun: 'Endler',
    nomScientifique: 'Poecilia wingei',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 120,
    slug: 'bristlenose-ancistrus-nain',
    categorie: 'Eau Douce',
    nomCommun: 'Bristlenose (ancistrus nain)',
    nomScientifique: 'Ancistrus cirrhosus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 121,
    slug: 'poisson-chat-synodontis',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat Synodontis',
    nomScientifique: 'Synodontis nigriventris',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 122,
    slug: 'poisson-chat-corydoras-venezuela',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat Corydoras venezuela',
    nomScientifique: 'Corydoras venezuelanus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 123,
    slug: 'poisson-pierre',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-pierre',
    nomScientifique: 'Erpetoichthys calabaricus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 124,
    slug: 'anguille-serpent-mastacembelus',
    categorie: 'Eau Douce',
    nomCommun: 'Anguille-serpent (Mastacembelus)',
    nomScientifique: 'Mastacembelus armatus',
    statutLegal: 'autorise',
    remarqueLegale: 'taille adulte importante et comportement à part - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 125,
    slug: 'perche-soleil-naine-decorative',
    categorie: 'Bassin',
    nomCommun: 'Perche soleil naine décorative',
    nomScientifique: 'Enneacanthus chaetodon',
    statutLegal: 'autorise',
    remarqueLegale: 'à ne pas confondre avec la perche-soleil Lepomis gibbosus (interdite) - vérifier le nom d\'espèce exact avant tout ajout en base',
    citesAnnexe: null,
  },
  {
    id: 126,
    slug: 'poisson-papillon',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-papillon',
    nomScientifique: 'Chaetodon auriga',
    statutLegal: 'autorise',
    remarqueLegale: 'alimentation souvent corallivore et taux de survie faible en captivité pour certaines espèces - à valider au cas par cas selon l\'espèce précise',
    citesAnnexe: null,
  },
  {
    id: 127,
    slug: 'poisson-ange-royal',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-ange royal',
    nomScientifique: 'Pygoplites diacanthus',
    statutLegal: 'autorise',
    remarqueLegale: 'alimentation spécialisée (éponges) et taux de survie faible en captivité - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 128,
    slug: 'cardinalis-de-banggai',
    categorie: 'Eau de Mer',
    nomCommun: 'Cardinalis de Banggai',
    nomScientifique: 'Pterapogon kauderni',
    statutLegal: 'autorise',
    remarqueLegale: 'espèce menacée à l\'état sauvage mais élevage en captivité très répandu - non listée CITES à ce jour, vérifier périodiquement',
    citesAnnexe: null,
  },
  {
    id: 129,
    slug: 'poisson-mandarin',
    categorie: 'Eau de Mer',
    nomCommun: 'Poisson-mandarin',
    nomScientifique: 'Synchiropus splendidus',
    statutLegal: 'autorise',
    remarqueLegale: 'alimentation très spécialisée (copépodes vivants) et taux de mortalité élevé chez le débutant - à valider au cas par cas',
    citesAnnexe: null,
  },
  {
    id: 130,
    slug: 'gobie-nemateleotris',
    categorie: 'Eau de Mer',
    nomCommun: 'Gobie némateleotris',
    nomScientifique: 'Nemateleotris magnifica',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 131,
    slug: 'demoiselle-a-trois-bandes',
    categorie: 'Eau de Mer',
    nomCommun: 'Demoiselle à trois bandes',
    nomScientifique: 'Dascyllus aruanus',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 132,
    slug: 'crevette-harlequin',
    categorie: 'Eau de Mer',
    nomCommun: 'Crevette Harlequin',
    nomScientifique: 'Hymenocera picta',
    statutLegal: 'autorise',
    remarqueLegale: 'se nourrit exclusivement d\'étoiles de mer - à déconseiller mais pas interdit',
    citesAnnexe: null,
  },
  {
    id: 133,
    slug: 'crabe-porcelaine',
    categorie: 'Eau de Mer',
    nomCommun: 'Crabe porcelaine',
    nomScientifique: 'Neopetrolisthes maculata',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 134,
    slug: 'corail-cuir-sinularia',
    categorie: 'Eau de Mer',
    nomCommun: 'Corail cuir (Sinularia)',
    nomScientifique: 'Sinularia sp.',
    statutLegal: 'autorise',
    remarqueLegale: 'corail mou non scléractiniaire, généralement non listé CITES',
    citesAnnexe: null,
  },
  {
    id: 135,
    slug: 'zoanthaire',
    categorie: 'Eau de Mer',
    nomCommun: 'Zoanthaire',
    nomScientifique: 'Zoanthus sp.',
    statutLegal: 'autorise',
    remarqueLegale: 'certaines colonies peuvent sécréter une toxine dangereuse (palytoxine) - à signaler pour rappel des précautions à l\'acheteur, pas d\'interdiction',
    citesAnnexe: null,
  },
  {
    id: 136,
    slug: 'requin-taupe-requin-de-recif-aquarium-geant',
    categorie: 'Eau de Mer',
    nomCommun: 'Requin taupe / requin de récif (aquarium géant)',
    nomScientifique: 'Chiloscyllium punctatum',
    statutLegal: 'autorise',
    remarqueLegale: 'requins listés CITES Annexe II selon l\'espèce, taille adulte incompatible avec un aquarium domestique standard - ne jamais autoriser en libre-service',
    citesAnnexe: null,
  },
  {
    id: 137,
    slug: 'crevette-blue-dream',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette Blue Dream',
    nomScientifique: 'Neocaridina davidi (var. bleue)',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 138,
    slug: 'crevette-tigre',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crevette Tigre',
    nomScientifique: 'Caridina cantonensis (var. tigre)',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 139,
    slug: 'escargot-tylomelania',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot Tylomelania',
    nomScientifique: 'Tylomelania sp.',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 140,
    slug: 'bacopa-caroliniana',
    categorie: 'Plantes',
    nomCommun: 'Bacopa caroliniana',
    nomScientifique: 'Bacopa caroliniana',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 141,
    slug: 'limnophila-sessiliflora',
    categorie: 'Plantes',
    nomCommun: 'Limnophila sessiliflora',
    nomScientifique: 'Limnophila sessiliflora',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 142,
    slug: 'riccia-fluitans',
    categorie: 'Plantes',
    nomCommun: 'Riccia fluitans',
    nomScientifique: 'Riccia fluitans',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 143,
    slug: 'cryptocoryne-parva',
    categorie: 'Plantes',
    nomCommun: 'Cryptocoryne parva',
    nomScientifique: 'Cryptocoryne parva',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 144,
    slug: 'hydrocotyle-leucocephala-trefle-d-eau',
    categorie: 'Plantes',
    nomCommun: 'Hydrocotyle leucocephala (trèfle d\'eau)',
    nomScientifique: 'Hydrocotyle leucocephala',
    statutLegal: 'autorise',
    remarqueLegale: 'à ne pas confondre avec Hydrocotyle ranunculoides (interdite) - vérifier le nom d\'espèce exact avant tout ajout en base',
    citesAnnexe: null,
  },
  {
    id: 145,
    slug: 'eleocharis-herbe-aiguille',
    categorie: 'Plantes',
    nomCommun: 'Eleocharis / herbe aiguille',
    nomScientifique: 'Eleocharis acicularis',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 146,
    slug: 'pogostemon-helferi',
    categorie: 'Plantes',
    nomCommun: 'Pogostemon helferi',
    nomScientifique: 'Pogostemon helferi',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 147,
    slug: 'ceratophyllum-demersum',
    categorie: 'Plantes',
    nomCommun: 'Ceratophyllum demersum',
    nomScientifique: 'Ceratophyllum demersum',
    statutLegal: 'autorise',
    remarqueLegale: null,
    citesAnnexe: null,
  },
  {
    id: 148,
    slug: 'gourami-dore',
    categorie: 'Eau Douce',
    nomCommun: 'Gourami doré',
    nomScientifique: 'Trichopodus trichopterus',
    statutLegal: 'autorise',
    remarqueLegale: 'Ajoutee automatiquement suite a une demande de validation.',
    citesAnnexe: null,
  },
  {
    id: 149,
    slug: 'apistogramma-viejita',
    categorie: 'Eau Douce',
    nomCommun: 'Apistogramma viejita',
    nomScientifique: 'Apistogramma viejita',
    statutLegal: 'autorise',
    remarqueLegale: 'Ajoutee automatiquement suite a une demande de validation.',
    citesAnnexe: null,
  },
  {
    id: 150,
    slug: 'hypancistrus-zebra-l046',
    categorie: 'Eau Douce',
    nomCommun: 'Hypancistrus zebra (L046)',
    nomScientifique: 'Hypancistrus zebra',
    statutLegal: 'autorise',
    remarqueLegale: 'Annexe C reglement CE 338/97 (CITES) : encadre l\'import/export international, pas la revente en France une fois legalement dans l\'UE. Declaration d\'elevage captif demandee au vendeur par precaution.',
    citesAnnexe: 'C',
  },
  {
    id: 151,
    slug: 'ecrevisse-americaine',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse américaine',
    nomScientifique: 'Orconectes limosus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 152,
    slug: 'ecrevisse-calico',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse calico',
    nomScientifique: 'Faxonius immunis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 153,
    slug: 'ecrevisse-commune-australie',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse commune (Australie)',
    nomScientifique: 'Cherax destructor',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 154,
    slug: 'myriophylle-du-bresil',
    categorie: 'Plantes',
    nomCommun: 'Myriophylle du Brésil',
    nomScientifique: 'Myriophyllum aquaticum',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 155,
    slug: 'salvinie-geante',
    categorie: 'Plantes',
    nomCommun: 'Salvinie géante',
    nomScientifique: 'Salvinia molesta',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 156,
    slug: 'faux-hygrophile',
    categorie: 'Plantes',
    nomCommun: 'Faux hygrophile',
    nomScientifique: 'Gymnocoronis spilanthoides',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 157,
    slug: 'gambusie',
    categorie: 'Eau Douce',
    nomCommun: 'Gambusie',
    nomScientifique: 'Gambusia affinis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 158,
    slug: 'escargot-pomme',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot-pomme',
    nomScientifique: 'Pomacea maculata',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE - à ne pas confondre avec l\'escargot mystère (Pomacea bridgesii) qui reste autorisé.',
    citesAnnexe: null,
  },
  {
    id: 159,
    slug: 'pseudorasbora-goujon-asiatique',
    categorie: 'Eau Douce',
    nomCommun: 'Pseudorasbora / goujon asiatique',
    nomScientifique: 'Pseudorasbora parva',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 160,
    slug: 'escargot-pomme-2',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot-pomme',
    nomScientifique: 'Pomacea canaliculata',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE - à ne pas confondre avec l\'escargot mystère (Pomacea bridgesii) qui reste autorisé.',
    citesAnnexe: null,
  },
  {
    id: 161,
    slug: 'choquemort',
    categorie: 'Eau Douce',
    nomCommun: 'Choquemort',
    nomScientifique: 'Fundulus heteroclitus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 162,
    slug: 'jussie-rampante',
    categorie: 'Plantes',
    nomCommun: 'Jussie rampante',
    nomScientifique: 'Ludwigia peploides',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE - à ne pas confondre avec Ludwigia repens qui reste autorisée.',
    citesAnnexe: null,
  },
  {
    id: 163,
    slug: 'vivipare-chinoise',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Vivipare chinoise',
    nomScientifique: 'Cipangopaludina chinensis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 164,
    slug: 'crabe-chinois',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Crabe chinois',
    nomScientifique: 'Eriocheir sinensis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 165,
    slug: 'ecrevisse-a-pinces-bleues',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse à pinces bleues',
    nomScientifique: 'Orconectes virilis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 166,
    slug: 'ecrevisse-de-californie-ecrevisse-signal',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse de Californie / écrevisse signal',
    nomScientifique: 'Pacifastacus leniusculus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 167,
    slug: 'jacinthe-d-eau',
    categorie: 'Plantes',
    nomCommun: 'Jacinthe d\'eau',
    nomScientifique: 'Eichhornia crassipes',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 168,
    slug: 'ecrevisse-de-louisiane',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse de Louisiane',
    nomScientifique: 'Procambarus clarkii',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
    fiche: {
      description:
        "L'écrevisse de Louisiane est classée parmi les espèces exotiques envahissantes les plus problématiques de France métropolitaine. Elle creuse des galeries qui fragilisent les berges des cours d'eau et étangs, se reproduit très rapidement, et est porteuse saine de la peste de l'écrevisse — une maladie mortelle pour les espèces d'écrevisses autochtones qu'elle contamine sans en souffrir elle-même.",
      conseil:
        "Cette espèce ne doit en aucun cas être achetée, vendue, transportée ou relâchée dans la nature en France (réglementation UE sur les espèces exotiques envahissantes). Si vous en observez dans un plan d'eau, signalez-le à la fédération de pêche locale plutôt que d'intervenir vous-même.",
      volumeMinLitres: null,
      tailleGroupeMin: null,
      compatibilite: "Non applicable : espèce interdite à la vente et à la détention en France.",
      incompatibilite: "Très territoriale et agressive envers tout cohabitant, y compris ses propres congénères ; creuse et s'échappe facilement des bassins non sécurisés.",
      phMin: 6.5,
      phMax: 8,
      tempMin: 15,
      tempMax: 25,
      difficulte: 'Intermédiaire',
      alimentation: "Omnivore opportuniste : végétaux, invertébrés, œufs et alevins de poissons, cadavres.",
      tailleAdulte: '10 à 12 cm',
    },
  },
  {
    id: 169,
    slug: 'hydrocotyle-fausse-renoncule',
    categorie: 'Plantes',
    nomCommun: 'Hydrocotyle fausse-renoncule',
    nomScientifique: 'Hydrocotyle ranunculoides',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE - à ne pas confondre avec Hydrocotyle leucocephala qui reste autorisée.',
    citesAnnexe: null,
  },
  {
    id: 170,
    slug: 'poisson-meteo-raye',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-météo rayé',
    nomScientifique: 'Misgurnus bipartitus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 171,
    slug: 'laitue-d-eau',
    categorie: 'Plantes',
    nomCommun: 'Laitue d\'eau',
    nomScientifique: 'Pistia stratiotes',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 172,
    slug: 'crassule-de-helms',
    categorie: 'Plantes',
    nomCommun: 'Crassule de Helms',
    nomScientifique: 'Crassula helmsii',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 173,
    slug: 'escargot-geant',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Escargot géant',
    nomScientifique: 'Marisa cornuarietis',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 174,
    slug: 'cabomba-eventail-de-caroline',
    categorie: 'Plantes',
    nomCommun: 'Cabomba / éventail de Caroline',
    nomScientifique: 'Cabomba caroliniana',
    statutLegal: 'cites_a_signaler',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 175,
    slug: 'myriophylle-heterophylle',
    categorie: 'Plantes',
    nomCommun: 'Myriophylle hétérophylle',
    nomScientifique: 'Myriophyllum heterophyllum',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 176,
    slug: 'perche-soleil',
    categorie: 'Eau Douce',
    nomCommun: 'Perche soleil',
    nomScientifique: 'Lepomis gibbosus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 177,
    slug: 'goujon-de-l-amour',
    categorie: 'Eau Douce',
    nomCommun: 'Goujon de l\'Amour',
    nomScientifique: 'Perccottus glenii',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 178,
    slug: 'jussie-a-grandes-fleurs',
    categorie: 'Plantes',
    nomCommun: 'Jussie à grandes fleurs',
    nomScientifique: 'Ludwigia grandiflora',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE - à ne pas confondre avec Ludwigia repens qui reste autorisée.',
    citesAnnexe: null,
  },
  {
    id: 179,
    slug: 'poisson-chat-noir-americain',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-chat noir américain',
    nomScientifique: 'Ameiurus melas',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 180,
    slug: 'ecrevisse-a-taches-rouges',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse à taches rouges',
    nomScientifique: 'Faxonius rusticus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 181,
    slug: 'moule-pygmee',
    categorie: 'Mollusques eau douce',
    nomCommun: 'Moule pygmée',
    nomScientifique: 'Limnoperna fortunei',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 182,
    slug: 'poisson-tete-de-serpent-du-nord',
    categorie: 'Eau Douce',
    nomCommun: 'Poisson-tête-de-serpent du Nord',
    nomScientifique: 'Channa argus',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France/UE.',
    citesAnnexe: null,
  },
  {
    id: 183,
    slug: 'elodee-de-nuttall',
    categorie: 'Plantes',
    nomCommun: 'Élodée de Nuttall',
    nomScientifique: 'Elodea nuttallii',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 184,
    slug: 'gambusie-2',
    categorie: 'Eau Douce',
    nomCommun: 'Gambusie',
    nomScientifique: 'Gambusia holbrooki',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en France.',
    citesAnnexe: null,
  },
  {
    id: 185,
    slug: 'grand-lagarosiphon',
    categorie: 'Plantes',
    nomCommun: 'Grand Lagarosiphon',
    nomScientifique: 'Lagarosiphon major',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE.',
    citesAnnexe: null,
  },
  {
    id: 186,
    slug: 'ecrevisse-marbree',
    categorie: 'Crustacés / Invertébrés eau douce',
    nomCommun: 'Écrevisse marbrée',
    nomScientifique: 'Procambarus fallax',
    statutLegal: 'interdite',
    remarqueLegale: 'Espèce exotique envahissante réglementée en UE (auto-clonage).',
    citesAnnexe: null,
  },
];
// Seules les espèces avec une fiche rédigée ont une page publiée — le
// catalogue ci-dessus peut lister une espèce avant que sa fiche existe,
// sans que ça ne crée de page vide/fine indexable par Google.
export const ESPECES_PUBLIEES: (Espece & { fiche: FicheTechnique })[] = ESPECES.filter(
  (e): e is Espece & { fiche: FicheTechnique } => Boolean(e.fiche)
);

export function fetchEspeceParSlug(slug: string): (Espece & { fiche: FicheTechnique }) | null {
  return ESPECES_PUBLIEES.find((e) => e.slug === slug) ?? null;
}

// Catégorie d'annonce (celle utilisée par /categorie/[slug]) correspondant à
// une catégorie d'espèce : tout ce qui est vivant (poissons, crevettes,
// coraux, mollusques) tombe dans "Vivant", les plantes dans "Plantes".
export function categorieAnnonceSlug(categorie: CategorieEspece): string {
  return categorie === 'Plantes' ? 'plantes' : 'vivant';
}

// Biotope (celui utilisé par /biotope/[slug]) correspondant à une catégorie
// d'espèce — les plantes d'aquarium vendues sur Aquatopia sont
// essentiellement des plantes d'eau douce.
export function biotopeSlug(categorie: CategorieEspece): 'eau-douce' | 'eau-de-mer' | 'bassin' {
  if (categorie === 'Eau de Mer') return 'eau-de-mer';
  if (categorie === 'Bassin') return 'bassin';
  return 'eau-douce';
}
